In [1]:
using Revise 
using Pkg
Pkg.activate(".")

using Graphs
using Random
using SimpleWeightedGraphs
using SparseArrays
using StatsBase

  Activating project at `~/git/CommunityDetectionAlgorithms.jl`


In [17]:
Pkg.rm("IterativeHeaps")

    Updating `~/git/CommunityDetectionAlgorithms.jl/Project.toml`
  [a4c9077e] - IterativeHeaps v1.1.0 `~/git/IterativeHeaps.jl`
    Updating `~/git/CommunityDetectionAlgorithms.jl/Manifest.toml`
  [a4c9077e] - IterativeHeaps v1.1.0 `~/git/IterativeHeaps.jl`


In [2]:
# USE THESE PACKAGES FOR NOW

# load IterativeHeaps
using Pkg
Pkg.develop(url = "/Users/usuario/git/IterativeHeaps.jl")
using IterativeHeaps

# load GraphDistanceAlgorithms
Pkg.develop(path = "https://github.com/jcsyme/GraphDistanceAlgorithms.jl")
using GraphDistanceAlgorithms

# get the graph fragments package
Pkg.develop(path = "https://github.com/jcsyme/GraphFragments.jl/")
using GraphFragments

# get the DiscreteGraphAlgorithms package
Pkg.develop(path = "https://github.com/jcsyme/DiscreteGraphAlgorithms.jl/")
using DiscreteGraphAlgorithms

   Resolving package versions...
  No Changes to `~/git/CommunityDetectionAlgorithms.jl/Project.toml`
  No Changes to `~/git/CommunityDetectionAlgorithms.jl/Manifest.toml`
     Cloning git-repo `https://github.com/jcsyme/GraphDistanceAlgorithms.jl`
Path `/Users/usuario/.julia/dev/GraphDistanceAlgorithms` exists and looks like the correct repo. Using existing path.
   Resolving package versions...
    Updating `~/git/CommunityDetectionAlgorithms.jl/Project.toml`
  [3fdb58ca] + GraphDistanceAlgorithms v0.1.0 `~/.julia/dev/GraphDistanceAlgorithms`
    Updating `~/git/CommunityDetectionAlgorithms.jl/Manifest.toml`
  [aaf54ef3] + DistributedArrays v0.6.7
  [3fdb58ca] + GraphDistanceAlgorithms v0.1.0 `~/.julia/dev/GraphDistanceAlgorithms`
  [18e54dd8] + IntegerMathUtils v0.1.2
  [27ebfcd6] + Primes v0.5.7
  [0dad84c5] + ArgTools v1.1.1
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [b27032c2] + LibCURL v0.6.4
  [76f85450] + LibGit2
  [56ddb016] + Logging
  [ca575930] + Network

In [191]:
include(joinpath("src", "CommunityDetectionAlgorithms.jl"))

[ Info: Temprary import structure... Build CommunityDetectionAlgorithms module


singleton_partition

In [5]:
# use this as a test
fp_egl = "/Users/usuario/git/DiscreteGraphAlgorithms.jl/ref/krebs.egl"
graph_wrapper = read_egl(fp_egl);
#graph = copy(graph_wrapper_dprk_undir.graph)


j, i, w = findnz(graph_wrapper.A)
w = Random.rand(length(w))
graph = SimpleWeightedGraph(j, i, w, );





In [176]:
# vertex_weight = Random.rand(nv(graph)) )
partition.partition_aux

62-element Vector{Int64}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [179]:
x = collect(1:10)

x[3], x[8] = x[8], x[3]

x

10-element Vector{Int64}:
  1
  2
  8
  4
  5
  6
  7
  3
  9
 10

In [247]:
#include(joinpath("src", "Leiden.jl"))


k = StatsBase.sample(10:20)

vec_membership = StatsBase.sample(1:k, nv(graph));
vec_membership_aux = zeros(Int64, nv(graph), );
reindex_membership!(vec_membership; membership_aux = vec_membership_aux, )


partition = GraphPartition1(graph; membership = vec_membership, )





vec_comm_size = zeros(Float64, size(vec_membership));
vec_deg = degree(graph)
vec_degrees_inv = 1 ./ vec_deg
gamma = 0.1

@time hamiltonian = hamiltonian_constant_potts_unsafe!(
    vec_membership,
    vec_comm_size,
    vec_degrees_inv,
    gamma,
    graph,
)

print(k)
sum(vec_comm_size[1:k])
hamiltonian


  0.000026 seconds (9 allocations: 7.500 KiB)
11

-31.23927309861461

In [248]:
k

11

In [264]:
propertynames(partition)

(:element_size, :element_weight, :graph_shape, :max_vertex_size, :membership, :membership_aux, :partition_aux, :partition_aux_fl, :partition_size, :vertex_weight)

In [262]:
graph
incidence = get_incidence_list(graph);


In [223]:
include(joinpath("src", "CommunityDetectionAlgorithms.jl"))

[ Info: Temprary import structure... Build CommunityDetectionAlgorithms module


singleton_partition

In [246]:
propertynames(partition)

(:element_size, :element_weight, :graph_shape, :max_vertex_size, :membership, :membership_aux, :partition_aux, :partition_aux_fl, :partition_size, :vertex_weight)

In [77]:
VECTOR(edge_weights_per_cluster)[current_cluster] - VECTOR(*node_weights)[v] * VECTOR(cluster_weights)[current_cluster] * resolution_parameter;





true

In [78]:
propertynames(partition)

(:element_size, :element_weight, :graph_shape, :max_vertex_size, :membership, :membership_aux, :partition_aux, :partition_size, :vertex_weight)

In [15]:
Pkg.rm("IterativeHeaps")

    Updating `~/git/CommunityDetectionAlgorithms.jl/Project.toml`
  [e285971d] - IterativeHeaps v0.1.0 `~/git/IterativeHeaps.jl`
  No Changes to `~/git/CommunityDetectionAlgorithms.jl/Manifest.toml`


In [37]:
import IterativeHeaps: fill_and_randomize_queue!
function fill_and_randomize_queue!(
    queue::SimpleQueue{T},
    n::Int64,
) where {T}
    reset!(queue)
    heap_push!(
        queue,
        shuffle(1:max(min(queue.max_size, n), 0))
    )
    
    return nothing
end

function fill_and_randomize_queue!(
    queue::SimpleQueue{T},
) where {T}
    fill_and_randomize_queue!(
        queue,
        queue.max_size,
    )
    
    return nothing
end




fill_and_randomize_queue! (generic function with 2 methods)

In [40]:
fill_and_randomize_queue!(queue_unstable, )


LoadError: MethodError: no method matching reset!(::SimpleQueue{Int64})

stack_pop! (generic function with 1 method)

In [765]:
stack_test = FixedStack1{Int64}(5)

FixedStack1{Int64}(0, [0, 0, 0, 0, 0], 5, [0])

In [744]:
for v in vec
    stack_push!(stack_test, v)
end

[ Info: Stack is full with 5 elements. Cannot push.
[ Info: Stack is full with 5 elements. Cannot push.
[ Info: Stack is full with 5 elements. Cannot push.


In [756]:
stack_pop!(stack_test)

In [763]:
stack_test

FixedStack1{Int64}(0, [0, 0, 0, 0, 0], 5, [0])

##  Start building move nodes routine

In [104]:

"""
Create a structure to store some shared vectors that are used 
    repeatedly throughout the calculation of 

"""
struct MoveNodesVectorBundle1
    n::Int64
    membership::Vector{Int64}
    neighbors::Vector{Int64}
    neighbors_added::Vector{Bool}
    size::Vector{Int64}
    weights::Union{Vector{Float64}, Vector{Int64}}
    vec_verts_stable_q::Vector{Bool}
    vec_verts_unstable::Vector{Int64}
    
    function MoveNodesVectorBundle1(
        graph::Union{AbstractGraph, SimpleWeightedGraph};
        membership::VecOrNoth{Int64} = nothing,
        neighbors::VecOrNoth{Int64} = nothing,
        neighbors_added::VecOrNoth{Bool} = nothing,
        size::VecOrNoth{Int64} = nothing,
        weights::Union{VecOrNoth{Float64}, VecOrNoth{Int64}} = nothing,
        vec_verts_stable_q::VecOrNoth{Bool} = nothing,
        vec_verts_unstable::VecOrNoth{Int64} = nothing, # this is the queue
    )
        # initialize sizing parameter
        n = nv(graph)
    
        
        ##  INITIALIZE VECTORS
        
        # community membership; 
        membership = initialize_vector(
            membership, 
            n,
            Int64;
            fill_func = nothing,
        )

        # additional storage vectors
        neighbors = initialize_vector(neighbors, n, Int64)
        neighbors_added = initialize_vector(neighbors_added, n, Bool)
        size = initialize_vector(size, n, Int64)
        weights = initialize_vector(weights, n, eltype(Graphs.weights(graph)))
        vec_verts_stable_q = initialize_vector(vec_verts_stable_q, n, Bool)
        vec_verts_unstable = initialize_vector(vec_verts_unstable, n, Int64)
        
        
        # update the queue as 1:n 
        vec_verts_unstable .= 1:n
        
        # return the output
        return new(
            n,
            neighbors,
            neighbors_added,
            size,
            weights,
            vec_verts_stable_q,
            vec_verts_unstable, 
        )
        
    end
end



"""
Prepare vectors for use in the MoveNodes function

# Constructs

```
prepare_move_nodes_vectors!(
    bundle::MoveNodesVectorBundle1;
)


##  Function Arguments

- `bundle`: MoveNodesVectorBundle1 to update before calculating differences
    and choosing next community
```


"""
function prepare_move_nodes_vectors!(
    bundle::MoveNodesVectorBundle1;
)
    # initialize vector fills
    fill!(bundle.vec_comm_neighbors, 0) # 
    fill!(bundle.vec_comm_neighbors_added, 0) # clear, all are false
    fill!(bundle.vec_comm_size, 0) # all comms set to 0
    fill!(bundle.vec_comm_weights, 0)
    fill!(bundle.vec_verts_stable_q, 0)
    
    # update and shuffle the queue index
    bundle.vec_verts_unstable .= 1:bundle.n
    StatsBase.shuffle!(bundle.vec_verts_unstable)
end



bundle = MoveNodesVectorBundle1(graph)
prepare_move_nodes_vectors!(bundle);




function move_nodes!(
    partition::AbstractPartition,
)



In [52]:
?shuffle

search: shuffle shuffle!



```
shuffle([rng=default_rng(),] v::AbstractArray)
```

Return a randomly permuted copy of `v`. The optional `rng` argument specifies a random number generator (see [Random Numbers](@ref)). To permute `v` in-place, see [`shuffle!`](@ref). To obtain randomly permuted indices, see [`randperm`](@ref).

# Examples

```jldoctest
julia> rng = MersenneTwister(1234);

julia> shuffle(rng, Vector(1:10))
10-element Vector{Int64}:
  6
  1
 10
  2
  3
  9
  5
  7
  4
  8
```

---

```
shuffle([rng=GLOBAL_RNG,] df::AbstractDataFrame)
```

Return a copy of `df` with randomly permuted rows. The optional `rng` argument specifies a random number generator.

Metadata: this function preserves table-level and column-level `:note`-style metadata.

# Examples

```jldoctest
julia> using Random

julia> rng = MersenneTwister(1234);

julia> shuffle(rng, DataFrame(a=1:5, b=1:5))
5×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     2      2
   2 │     1      1
   3 │     4      4
   4 │     3      3
   5 │     5      5
```


In [386]:
edge = 1
for edge2 in edges(graph)
    edge = edge2
end
propertynames(edge)
edge.src

61

In [64]:
queue = SimpleQueue2{Int64}(
    119;
    force_unsafe_index_init = true,
    index = StatsBase.shuffle(collect(1:119)),
)

SimpleQueue2{Int64}([63, 64, 34, 51, 11, 33, 37, 98, 87, 67  …  57, 117, 75, 53, 76, 15, 88, 99, 96, 108], [119], 119, 0)

In [122]:
x = collect(1:15)

IterativeHeaps.initialize_vector(x, 15; fill_func = nothing, )


15-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

In [101]:
@time for i in 1:10
    x[i] = i
end

  0.000006 seconds


In [ ]:
vv = nothing
vv = vv, 10, Bool)



initialize_vector(

10-element Vector{Bool}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [ ]:
function delta_hamiltonian_constant_potts(
    v::Int64,
    vec_membership::Vector{Int64};
    vec_comm_size::Vector
)
    
    adj = neighbors(graph, vertex)
    
    # iterate over neighbors to determine which are in the same comm
    for u in adj
        if vec_membership[u] == vec_membership[v]
            
        end
    end
    
    
end

In [9]:
VecOrNoth{T} = Union{Vector{T}, Nothing}

Union{Nothing, Vector{T}} where T

In [33]:
v .= 1:2

2-element Vector{Real}:
 1
 2

In [6]:
e2 = nothing

for (i, e) in enumerate(edges(graph))
    (i < 10) && println(e)
    (i == 1) && (e2 = e)
end

Edge 3 => 7 with weight 1.1744968244044456
Edge 10 => 11 with weight 1.0207272120483042
Edge 4 => 34 with weight 1.3078873868102796
Edge 45 => 46 with weight 1.4506503952728669
Edge 45 => 47 with weight 0.5627383554134274
Edge 37 => 48 with weight 0.9572967380909618
Edge 14 => 63 with weight 0.710919263528397
Edge 17 => 66 with weight 0.7863439120316822
Edge 22 => 74 with weight 1.3505558013952115


In [333]:
membs = StatsBase.sample(1:30, nv(graph));

In [340]:
#
@time hamiltonian_constant_potts(
    membs,
    0.0001,
    graph,
)

  0.000007 seconds


-15.408025486787299

In [274]:



elementsz = zeros(Int64, size(vec_membership))

count_partition_sizes!(
    elementsz,
    vec_membership,
)






12

In [242]:
function aggregate_graph(
    graph::GGraph,
    paritition::GraphPartition6,
)

end


GraphPartition1([6, 3, 3, 6, 7, 7, 5, 4, 5, 9  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [10, 5, 5, 7, 12, 10, 5, 6, 10, 12  …  12, 1, 12, 9, 2, 9, 3, 11, 10, 6])

In [324]:
v = 2

dict_visited = Dict()
for u in outneighbors(graph, v)
    
    comm = membs[v]
    
    
    
    
end

24
24
24
24
24
24
24


In [45]:
x = zeros(Int64, 100)
x .= 1:100
x

100-element Vector{Int64}:
   1
   2
   3
   4
   5
   6
   7
   8
   9
  10
  11
  12
  13
   ⋮
  89
  90
  91
  92
  93
  94
  95
  96
  97
  98
  99
 100

In [128]:
#findall(x -> (x == 2), graph_wrapper_dprk_undir.A.colptr)
#outneighbors(graph_wrapper_dprk_undir.graph, 1)

In [327]:
resize!(x, 30, 9)

LoadError: MethodError: no method matching resize!(::Vector{Int64}, ::Int64, ::Int64)

Closest candidates are:
  resize!(::Vector, ::Integer)
   @ Base array.jl:1312
  resize!(::DataFrames.DataFrame, ::Integer)
   @ DataFrames ~/.julia/packages/DataFrames/58MUJ/src/dataframe/dataframe.jl:1073
  resize!(::MathOptInterface.Nonlinear.ReverseAD.Coloring.IndexedSet, ::Integer)
   @ MathOptInterface ~/.julia/packages/MathOptInterface/2CULs/src/Nonlinear/ReverseAD/Coloring/Coloring.jl:40
  ...


In [329]:
?resize!

search: resize!



```
resize!(a::Vector, n::Integer) -> Vector
```

Resize `a` to contain `n` elements. If `n` is smaller than the current collection length, the first `n` elements will be retained. If `n` is larger, the new elements are not guaranteed to be initialized.

# Examples

```jldoctest
julia> resize!([6, 5, 4, 3, 2, 1], 3)
3-element Vector{Int64}:
 6
 5
 4

julia> a = resize!([6, 5, 4, 3, 2, 1], 8);

julia> length(a)
8

julia> a[1:6]
6-element Vector{Int64}:
 6
 5
 4
 3
 2
 1
```

---

```
resize!(df::DataFrame, n::Integer)
```

Resize `df` to have `n` rows by calling `resize!` on all columns of `df`.

Metadata: this function preserves table-level and column-level `:note`-style metadata.

# Examples

```jldoctest
julia> df = DataFrame(a=1:3, b=4:6)
3×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      4
   2 │     2      5
   3 │     3      6

julia> resize!(df, 2)
2×2 DataFrame
 Row │ a      b
     │ Int64  Int64
─────┼──────────────
   1 │     1      4
   2 │     2      5
```


In [75]:
graph_wrapper_dprk_undir.dims

(2458, 7142)